config/routes.rb
Rails.application.routes.draw do
  # TODO: 総見直し
  # home
  root "home#top"
  get "about", to: "home#about"

  # パワプロ：選手作成メモ
  resources :pawapuro, except: [:show, :destroy] do
    collection do
      get "confirm", to: "pawapuro#confirm" # 選手作成確認画面
      # post "confirm", to: "pawapuro#confirm" # 選手作成確認画面
    end
    #  idを含むパス
    member do
      get "details", to: "pawapuro#details" # 選手詳細モーダル
    end
  end

  # エメラルドバトルフロンティア
  get "e_frontier", to: "e_frontier#index"
  get "e_frontier_search", to: "e_frontier#search"
  # resources :e_frontier, except: [:destroy] do
  #   collection do
  #     get :search # 全てのユーザに対する検索機能
  #   end
  # end

  # いいね
  resources :likes, only: [:create, :destroy], param: :post_id

  # ユーザ関連
  # （index, new, create, show, edit, update, destroy）
  # resourceのイメージは下記の通り
  # GET    /users          => users#index
  # GET    /users/new      => users#new
  # POST   /users          => users#create
  # GET    /users/:id      => users#show（user_path(@current_user)）
  # GET    /users/:id/edit => users#edit
  # PATCH  /users/:id      => users#update
  # PUT    /users/:id      => users#update
  # DELETE /users/:id      => users#destroy
  resources :users, except: [:destroy] do
    member do
      get :likes
      get :edit # ユーザ編集
      post :update # ユーザ変数のアクション
    end
  end

  # 投稿関連
  resources :posts, except: [:destroy] do
    member do
      get :edit # 投稿編集
      post :update # 投稿編集のアクション
      post :destroy # 投稿削除
    end
  end

  # ログイン、ログアウト、サインアップ
  get "login", to: "users#login_form"
  post "login", to: "users#login"
  post "logout", to: "users#logout"
  get "signup", to: "users#new"
end

app/controllers/e_frontier_controller.rb
class EFrontierController < ApplicationController
  # エメラルド：バトルフロンティア
  def index
    @hit_pokemon = []
  end

  # 検索ボタン押下
  def search
    @hit_pokemon = if params[:name].present?
                     EFrontierAll.search(params[:name], params[:lap])
                   else
                     []
                   end

    respond_to do |format|
      format.html { render "index" }
      format.js
    end
    # render :search
  end
end

app/helpers/e_frontier_helper.rb
module EFrontierHelper
end

app/views/e_frontier/_search_results.html.erb
<%# 検索結果一覧表示 %>
<div class="shadow">
  <ul class="list-group list-group-flush ">
    <% pokemons.each do |pokemon| %>
      <li class="list-group-item d-flex flex-row">
        <%= pokemon.name %>
        <%= pokemon.type1 %>
        <%= pokemon.type2 %>
        <%= pokemon.move1 %>
        <%= pokemon.move2 %>
        <%= pokemon.move3 %>
        <%= pokemon.move4 %>
        <%= pokemon.item %>
        <%= pokemon.effort_values %>
        <%= pokemon.character %>
      </li>
    <% end %>
  </ul>
</div>

app/views/e_frontier/index.html.erb
<%# エメラルド：バトルフロンティア %>
<div class="container">
  <h1>エメラルド：バトルフロンティア</h1>
  <%# 検索 %>
  <form class="mb-3">
    <%= form_with url: e_frontier_search_path, method: :get, local: false do |form| %>
      <%#= form_with url: search_e_frontier_index_path, method: :get, local: false do |form| %>
        <%# レベル50 or オープンレベル %>
        <div class="mb-3">
          <div class="form-check form-check-inline">
            <%= form.radio_button :level, '50', class: "form-check-input", id: "level50" %>
            <label class="form-check-label" for="level50">
              レベル50
            </label>
          </div>
          <div class="form-check form-check-inline">
            <%= form.radio_button :level, 'open', class: "form-check-input", id: "open-level", checked: true %>
            <label class="form-check-label" for="open-level">
              オープンレベル
            </label>
          </div>
        </div>
        <%# 周 %>
        <div class="mb-3">
          <label for="lap" class="form-label">周</label>
          <% if params[:level] == '50' %>
            <%= form.select :lap, options_for_select([['1周目', 1], ['2周目', 2], ['3周目', 3]], params[:lap].to_i), {}, class: "form-select", id: "lap" %>
          <% else %>
            <%= form.select :lap, options_for_select([ ['1周目', 4], ['2周目', 5], ['3周目', 6], ['4周目', 7], ['5周目', 8]], params[:lap].to_i), {}, class: "form-select", id: "lap" %>
          <% end %>
        </div>
        <%# ポケモン名 %>
        <div class="mb-3">
          <label for="pokemon_name" class="form-label">ポケモン名</label>
          <%= form.text_field :name, value: params[:name], id: "name", autocomplete: "search", class: "form-control" %>
        </div>
        <%# 検索ボタン %>
        <%= form.submit '検索', class: "btn btn-primary" %>
        <%# クリアボタン %>
        <%= form.submit 'クリア', type: :reset ,class: "btn btn-secondary" %>
      <% end %>
    </form>
    <%# 検索結果一覧表示 %>
    <div class="result" id="result">
      <%# TODO:下記はjsを経由していない。 %>
      <%= render partial: 'search_results', locals: { pokemons: @hit_pokemon } %>
    </div>
  </div>

app/views/e_frontier/search.js.erb
<%# _search_results.html.erbをレンダリングして、その結果を.result要素の中に挿入 %>
$("#result").html("<%= j render partial: 'search_results', locals: { pokemons: @hit_pokemon } %>");