config/routes.rb
Rails.application.routes.draw do
  # TODO: 総見直し
  # home
  root "home#top"
  get "about", to: "home#about"

  # パワプロ：選手作成メモ
  resources :pawapuro, except: [:show, :destroy] do
    collection do
      get "confirm", to: "pawapuro#confirm" # 選手作成確認画面
      # post "confirm", to: "pawapuro#confirm" # 選手作成確認画面
    end
    #  idを含むパス
    member do
      get "details", to: "pawapuro#details" # 選手詳細モーダル
    end
  end

  # エメラルドバトルフロンティア
  get "e_frontier", to: "e_frontier#index"
  get "e_frontier_search", to: "e_frontier#search"
  # resources :e_frontier, except: [:destroy] do
  #   collection do
  #     get :search # 全てのユーザに対する検索機能
  #   end
  # end

  # いいね
  resources :likes, only: [:create, :destroy], param: :post_id

  # ユーザ関連
  # （index, new, create, show, edit, update, destroy）
  # resourceのイメージは下記の通り
  # GET    /users          => users#index
  # GET    /users/new      => users#new
  # POST   /users          => users#create
  # GET    /users/:id      => users#show（user_path(@current_user)）
  # GET    /users/:id/edit => users#edit
  # PATCH  /users/:id      => users#update
  # PUT    /users/:id      => users#update
  # DELETE /users/:id      => users#destroy
  resources :users, except: [:destroy] do
    member do
      get :likes
      get :edit # ユーザ編集
      post :update # ユーザ変数のアクション
    end
  end

  # 投稿関連
  resources :posts, except: [:destroy] do
    member do
      get :edit # 投稿編集
      post :update # 投稿編集のアクション
      post :destroy # 投稿削除
    end
  end

  # ログイン、ログアウト、サインアップ
  get "login", to: "users#login_form"
  post "login", to: "users#login"
  post "logout", to: "users#logout"
  get "signup", to: "users#new"
end

app/controllers/pawapuro_controller.rb
class PawapuroController < ApplicationController
  # 選手一覧画面
  def index
    @players = PawapuroPlayer.all
  end

  # 選手詳細モーダル
  def details
    @player = PawapuroPlayer.find(params[:id])
    respond_to do |format|
      format.js # JavaScriptレスポンスを期待
      format.html # TODO: 暫定処置。非同期で上記が表示できるようになったら消す。
    end
  end

  # 選手作成入力画面
  def new
    @player = PawapuroPlayer.new
    @player.build_pawapuro_pitcher
    @player.build_pawapuro_fielder
    # @pitcher = PawapuroPitcher.new
    # @pfielder = PawapuroFielder.new
  end

  # 選手情報編集画面
  def edit
    @player = PawapuroPlayer.find(params[:id])
    # @pitcher = PawapuroPitcher.find(params[:id])
    # @pfielder = PawapuroFielder.find(params[:id])
  end

  # 選手作成アクション
  def create
    @player = PawapuroPlayer.new(player_params)
    # @pitcher = PawapuroPitcher.new(pitcher_params)
    # @pfielder = PawapuroFielder.new(fielder_params)
    if @player.save
      # 成功時の処理（例：リダイレクト）
      # redirect_to some_path, notice: 'Player was successfully created.'
      redirect_to pawapuro_index_path
    else
      # 失敗時の処理
      render :new
    end
  end

  # 選手編集アクション
  def update
    @player = PawapuroPlayer.find(params[:id])
    if @player.update(player_params)
      # 成功時の処理
      # redirect_to some_other_path, notice: 'Player was successfully updated.'
      redirect_to pawapuro_index_path
    else
      # 失敗時の処理
      render :edit
    end
    # @pitcher = PawapuroPitcher.find(params[:id])
    # @pfielder = PawapuroFielder.find(params[:id])
  end

  # 選手作成確認画面
  def confirm
    # @pawapuro = Pawapuro.new(pawapuro_params)
    # if @pawapuro.valid?
    #   render :confirm
    # else
    #   render :new
    # end
  end

  private

  def player_params
    params.require(:pawapuro_player).permit(
      :last_name, :first_name, :player_name, :back_name, :birthday, :throws, :bats, :main_position, :sub_position_2, :sub_position_3, :sub_position_4, :sub_position_5, :sub_position_6, :sub_position_7, :kaifuku, :kegasinikusa, :note,
      pawapuro_pitcher_attributes: [:id, :starter_proper, :reliever_proper, :closer_proper, :pace, :control, :stamina, :taipinch, :taihidaridasya, :utarezuyosa, :nobi, :quick],
      pawapuro_fielder_attributes: [:id, :trajectory, :meat, :power, :running, :arm_strength, :defense, :catching, :chance, :taihidaritousyu, :catcher, :tourui, :sourui, :soukyuu]
    )
  end
  # def pitcher_params
  #   pramas.requier(:pitcher).permit(:pace)
  # end
  # def fielder_params
  #   pramas.requier(:fielder).permit(:meat)
  # end
end

app/helpers/pawapuro_helper.rb
module PawapuroHelper
  # 数値をポジション名に変換
  def display_position_name(val)
    positions = {
      1 => "投",
      2 => "捕",
      3 => "一",
      4 => "二",
      5 => "三",
      6 => "遊",
      7 => "外"
    }
    content_tag(:span, positions[val] || "ERR")
  end

  # 特能数値をアルファベットに変換
  def display_special_ability_alphabet(val)
    abilities = {
      -3 => "G",
      -2 => "F",
      -1 => "E",
      0 => "D",
      1 => "C",
      2 => "B",
      3 => "A"
    }
    content_tag(:span, abilities[val] || "")
  end

  # 投打の値を右・左・両に変換
  def display_left_and_right(val)
    throws_bats = {
      "right" => "右",
      "left" => "左",
      "both" => "両"
    }
    content_tag(:span, throws_bats[val] || "")
  end

  # 能力値（弾道）によって文字色、→の角度を変更
  def display_trajectory(trajectory)
    text_color, angle = case trajectory
                        when 2
                          ["pawa-text-c", "-20deg"]
                        when 3
                          ["pawa-text-b", "-30deg"]
                        when 4
                          ["pawa-text-a", "-45deg"]
                        else
                          ["pawa-text-d", "-10deg"]
                        end
    content_tag(:i, "", class: "fa fa-solid fa-arrow-right #{text_color}", style: "transform: rotate(#{angle});")
  end

  # 能力値（弾道以外）をアルファベットに変換＋文字色変更
  def display_alphabet(val)
    case val
    when 1..29
      content_tag(:span, "G ", class: "pawa-text-g")
    when 30..39
      content_tag(:span, "F ", class: "pawa-text-f")
    when 40..49
      content_tag(:span, "E ", class: "pawa-text-e")
    when 50..59
      content_tag(:span, "D ", class: "pawa-text-d")
    when 60..69
      content_tag(:span, "C ", class: "pawa-text-c")
    when 70..79
      content_tag(:span, "B ", class: "pawa-text-b")
    when 80..89
      content_tag(:span, "A ", class: "pawa-text-a")
    when 90..100
      content_tag(:span, "S ", class: "pawa-text-s")
    else
      # エラーケース
      content_tag(:span, "", class: "")
    end
  end

  # ポジション表示
  # 2 から 7 までの数値をループ。
  # 各ループで、動的に sub_position_2, sub_position_3, ..., sub_position_7 の値を取得。
  # sub_position が0ではなく、かつその数値が main_position と異なる場合にのみ、そのポジションを表示用の配列に追加。
  # メインポジションは、太字で確定表示。
  # 最終的に、配列内の要素を「・」で結合して返却。
  def display_positions(player)
    positions = ["<strong>#{display_position_name(player.main_position)}</strong>"]

    (2..7).each do |num|
      sub_position = player.send("sub_position_#{num}")
      positions << display_position_name(num) if sub_position.to_i.nonzero? && num != player.main_position
    end
    positions.join("・").html_safe
  end

  # 属性名から位置番号を抽出（上記のdisplay_sub_positionsで使用）
  def position_number(attribute)
    attribute[-1].to_i
  end

  # 変化球ブロック
  # 変化量によって、色付きのブロックを表示する。
  def breaking_ball_blocks(pitcher, ball_type)
    Array.new(7) do |i|
      class_name = i < pitcher.send("#{ball_type}_type_movement") ? "pawa-breaking-block-exist" : "pawa-breaking-block-nil"
      content_tag(:div, "", class: "col-1 #{class_name}")
    end.join.html_safe
  end

  # 年齢計算
  def calculate_age(birthday)
    now = Time.zone.today
    age = now.year - birthday.year
    age -= 1 if now.yday < birthday.yday
    age
  end
end

app/views/pawapuro/_breaking_ball_meter.html.erb
<%# 変化球メーター %>
<%# 第二球種名 %>
<% second_pitch_type = @player.pawapuro_pitcher.send("second_#{breaking_ball_type}_type_pitch") %>
<%# 変化球名 %>
<div class="pawa-breaking-font">
  <%= @player.pawapuro_pitcher.send("#{breaking_ball_type}_type_pitch") %>
  <% if second_pitch_type.present? %>
    ・<%= second_pitch_type %>
  <% end %>
</div>
<div class="ms-3">
  <%# 第一球種 %>
  <div class="row">
    <%= breaking_ball_blocks(@player.pawapuro_pitcher, breaking_ball_type) %>
  </div>
  <%# 第二球種 %>
  <% if second_pitch_type.present? %>
    <div class="row">
      <%= breaking_ball_blocks(@player.pawapuro_pitcher, "second_#{breaking_ball_type}") %>
    </div>
  <% end %>
</div>

app/views/pawapuro/_fielder_basic_ability_wrap.html.erb
<%# 野手基礎能力部 %>
<div class="d-flex justify-content-start row border border-3 border-white rounded p-1 mb-1 pawa-bg-main">
  <div class="col-5 p-0">
    <div class="pawa-ability-label">弾道</div>
  </div>
  <div class="col-7 ps-3 py-2">
    <span class="pawa-text-a me-2 h5"><%= display_trajectory(@player.pawapuro_fielder.trajectory) %></span>
    <span class="h5"><%= @player.pawapuro_fielder.trajectory %></span>
  </div>
</div>
<div class="d-flex justify-content-start row border border-3 border-white rounded p-1 mb-1 pawa-bg-main">
  <div class="col-5 p-0">
    <div class="pawa-ability-label">ミート</div>
  </div>
  <div class="col-7 ps-3 py-2">
    <span class="me-2 h5"><%= display_alphabet(@player.pawapuro_fielder.meat) %></span>
    <span class="h5"><%= @player.pawapuro_fielder.meat %></span>
  </div>
</div>
<div class="d-flex justify-content-start row border border-3 border-white rounded p-1 mb-1 pawa-bg-main">
  <div class="col-5 p-0">
    <div class="pawa-ability-label">パワー</div>
  </div>
  <div class="col-7 ps-3 py-2">
    <span class="me-2 h5"><%= display_alphabet(@player.pawapuro_fielder.power) %></span>
    <span class="h5"><%= @player.pawapuro_fielder.power %></span>
  </div>
</div>
<div class="d-flex justify-content-start row border border-3 border-white rounded p-1 mb-1 pawa-bg-main">
  <div class="col-5 p-0">
    <div class="pawa-ability-label">走力</div>
  </div>
  <div class="col-7 ps-3 py-2">
    <span class="me-2 h5"><%= display_alphabet(@player.pawapuro_fielder.running) %></span>
    <span class="h5"><%= @player.pawapuro_fielder.running %></span>
  </div>
</div>
<div class="d-flex justify-content-start row border border-3 border-white rounded p-1 mb-1 pawa-bg-main">
  <div class="col-5 p-0">
    <div class="pawa-ability-label">肩力</div>
  </div>
  <div class="col-7 ps-3 py-2">
    <span class="me-2 h5"><%= display_alphabet(@player.pawapuro_fielder.arm_strength) %></span>
    <span class="h5"><%= @player.pawapuro_fielder.arm_strength %></span>
  </div>
</div>
<div class="d-flex justify-content-start row border border-3 border-white rounded p-1 mb-1 pawa-bg-main">
  <div class="col-5 p-0">
    <div class="pawa-ability-label">守備力</div>
  </div>
  <div class="col-7 ps-3 py-2">
    <span class="me-2 h5"><%= display_alphabet(@player.pawapuro_fielder.defense) %></span>
    <span class="h5"><%= @player.pawapuro_fielder.defense %></span>
  </div>
</div>
<div class="d-flex justify-content-start row border border-3 border-white rounded p-1 pawa-bg-main">
  <div class="col-5 p-0">
    <div class="pawa-ability-label">捕球</div>
  </div>
  <div class="col-7 ps-3 py-2">
    <span class="me-2 h5"><%= display_alphabet(@player.pawapuro_fielder.catching) %></span>
    <span class="h5"><%= @player.pawapuro_fielder.catching %></span>
  </div>
</div>

app/views/pawapuro/_player_datails_fielder.html.erb
<%# 野手能力 %>
<div class="row p-2">
  <%# 基礎能力部 %>
  <div class="col-3 pe-4 pawa-text-main">
    <%= render partial: 'fielder_basic_ability_wrap' %>
  </div>
  <%# 特殊能力部 %>
  <div class="col-9 bg-light border border-3 border-white rounded">
    <%# 値あり %>
    <div class="row">
      <%= render partial: 'special_ability_value_box', locals: { ability_name:"チャンス", ability_value: @player.pawapuro_fielder.chance } %>
      <%= render partial: 'special_ability_value_box', locals: { ability_name:"対左投手", ability_value: @player.pawapuro_fielder.taihidaritousyu } %>
      <%# TODO: テーブルに「キャッチャー」を追加 %>
      <div class="col fs-3 pawa-bg-sa-n1 rounded">
        <div class="row pt-1 pb-1 ps-1 text-center">
          <span class="col-10 pawa-bg-main rounded pawa-text-neutral">&nbsp;</span>
          <span class="col-2 ps-2 text-light"></span>
        </div>
      </div>
      <%= render partial: 'special_ability_value_box', locals: { ability_name:"ケガしにくさ", ability_value: @player.kegasinikusa } %>
    </div>
    <div class="row">
      <%= render partial: 'special_ability_value_box', locals: { ability_name:"盗塁", ability_value: @player.pawapuro_fielder.tourui } %>
      <%= render partial: 'special_ability_value_box', locals: { ability_name:"走塁", ability_value: @player.pawapuro_fielder.sourui } %>
      <%= render partial: 'special_ability_value_box', locals: { ability_name:"送球", ability_value: @player.pawapuro_fielder.soukyuu } %>
      <%= render partial: 'special_ability_value_box', locals: { ability_name:"回復", ability_value: @player.kaifuku } %>
    </div>
    <%# 値なし %>
    <%# FIXME: 部分テンプレートに切り出し %>
    <% abilities_array = @player.pawapuro_fielder.other_special_abilities.present? ? @player.pawapuro_fielder.other_special_abilities.split(',') : [] %>
    <% 6.times do |row| %>
      <div class="row">
        <% (row*4...row*4+4).each do |index| %>
          <% if abilities_array[index] %>
            <%= render partial: 'special_ability_no_value_box', locals: { ability: abilities_array[index] } %>
          <% else %>
            <%= render partial: 'special_ability_no_value_box', locals: { ability: '' } %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/pawapuro/_player_details_modal.html.erb
<%# 選手詳細モーダル %>
<div class="modal fade" id="playerDetailsModal" tabindex="-1" aria-labelledby="playerModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content pawa-bg-main">
      <div class="modal-body">
        <%# タブ %>
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a class="nav-link active" data-bs-toggle="tab" data-bs-target="#playerBasic">選手能力</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-bs-toggle="tab" data-bs-target="#playerPitcher">投手能力</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-bs-toggle="tab" data-bs-target="#playerFielder">野手能力</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-bs-toggle="tab" data-bs-target="#playerPromotion">守備・起用</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-bs-toggle="tab" data-bs-target="#playerProfile">プロフィール</a>
          </li>
        </ul>
        <div class="modal-body">
          <%# 基本情報部 %>
          <div class="d-flex justify-content-between">
            <h5 class="pawa-bg-sa-outfielder pawa-border-outfielder rounded px-4 py-1 mb-2 text-center h3" id="playerDetails">吉田正</h5>
            <div class="d-flex align-items-center pawa-text-main">
              <div class="p-0">
                <div class="pawa-ability-label">守備位置</div>
              </div>
              <span class="ms-1">
                <strong>外</strong>
              </span>
            </div>
            <div class="d-flex align-items-center pawa-text-main">
              <div class="p-0">
                <div class="pawa-ability-label">投打</div>
              </div>
              <span class="ms-1">
                <strong>右投左打</strong>
              </span>
            </div>
          </div>
          <%# 能力部 %>
          <div class="tab-content container-fluid pawa-bg-sub rounded">
            <%# 選手能力 %>
            <div class="tab-pane fade show active" id="playerBasic">
              <%# TODO: メインポジションが投手か野手によって、表示を分ける %>
              <%= render 'player_datails_fielder' %>
            </div>
            <%# 投手能力 %>
            <div class="tab-pane fade" id="playerPitcher">
              <%= render 'player_datails_pitcher' %>
            </div>
            <%# 野手能力 %>
            <div class="tab-pane fade" id="playerFielder">
              <%= render 'player_datails_fielder' %>
            </div>
            <%# 守備・起用 %>
            <div class="tab-pane fade" id="playerPromotion">
              <%= render 'player_datails_promotion' %>
            </div>
            <%# プロフィール %>
            <div class="tab-pane fade" id="playerProfile">
              <%= render 'player_datails_profile' %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= link_to '編集', edit_pawapuro_path(1), class: 'btn btn-primary' %>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pawapuro/confirm.html.erb
<div class="container">
  <h1>パワプロ：入力内容確認</h1>
  <div>※まだ登録は完了していません</div>
  <div>下記の内容で登録します。よろしいですか？</div>
  <%#= form_for @pawapuro, url: pawapuro_path do |f| %>
    <!-- ここに確認するデータの表示 -->
    <%#= f.submit "登録する" %>
    <%# end %>
  </div>

app/views/pawapuro/details.html.erb
<%# TODO: 当ファイルは最終的に不要。 %>
<div class="container">
  <h1>選手情報詳細</h1>
  <div class="modal-body">
    <%# タブ %>
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link active" data-bs-toggle="tab" data-bs-target="#playerBasic">選手能力</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="tab" data-bs-target="#playerPitcher">投手能力</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="tab" data-bs-target="#playerFielder">野手能力</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="tab" data-bs-target="#playerPromotion">守備・起用</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="tab" data-bs-target="#playerProfile">プロフィール</a>
      </li>
    </ul>
    <div class="modal-body">
      <%# 基本情報部 %>
      <div class="d-flex justify-content-between">
        <h5 class="pawa-bg-sa-outfielder pawa-border-outfielder rounded px-4 py-1 mb-2 text-center h3" id="playerDetails"><%= @player.player_name %></h5>
        <div class="d-flex align-items-center pawa-text-main">
          <div class="p-0">
            <div class="pawa-ability-label">守備位置</div>
          </div>
          <span class="ms-1">
            <%= display_positions(@player) %>
          </span>
        </div>
        <div class="d-flex align-items-center pawa-text-main">
          <div class="p-0">
            <div class="pawa-ability-label">投打</div>
          </div>
          <span class="ms-1">
            <strong><%= display_left_and_right(@player.throws) %>投<%= display_left_and_right(@player.bats) %>打</strong>
          </span>
        </div>
      </div>
      <%# 能力部 %>
      <div class="tab-content container-fluid pawa-bg-sub rounded">
        <%# 選手能力 %>
        <div class="tab-pane fade show active" id="playerBasic">
          <%# TODO: メインポジションが投手か野手によって、表示を分ける %>
          <%= render 'player_datails_fielder' %>
        </div>
        <%# 投手能力 %>
        <div class="tab-pane fade" id="playerPitcher">
          <%= render 'player_datails_pitcher' %>
        </div>
        <%# 野手能力 %>
        <div class="tab-pane fade" id="playerFielder">
          <%= render 'player_datails_fielder' %>
        </div>
        <%# 守備・起用 %>
        <div class="tab-pane fade" id="playerPromotion">
          <%= render 'player_datails_promotion' %>
        </div>
        <%# プロフィール %>
        <div class="tab-pane fade" id="playerProfile">
          <%= render 'player_datails_profile' %>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <%= link_to '編集', edit_pawapuro_path(1), class: 'btn btn-primary' %>
      <%= link_to '選手一覧に戻る', pawapuro_index_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/pawapuro/index.html.erb
<%# 作成選手一覧 %>
<div class="container">
  <h1>パワプロ：作成選手一覧</h1>
  <%# 検索 %>
  <%= link_to '新規選手作成', new_pawapuro_path, class: 'btn btn-primary' %>
  <form class="mb-3">
    <%# 投/野ラジオ %>
    <label class="form-label">表示能力</label>
    <div class="mb-3">
      <div class="form-check form-check-inline">
        <input class="form-check-input" name="formRadio" type="radio" id="formRadioPitcher">
        <label class="form-check-label" for="formRadioPitcher">
          投手
        </label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" name="formRadio" type="radio" id="formRadioFielder" checked>
        <label class="form-check-label" for="formRadioFielder">
          野手
        </label>
      </div>
    </div>
    <%# 選手名 %>
    <div class="mb-3">
      <label for="name" class="form-label">選手名</label>
      <input type="search" class="form-control" id="name" autocomplete="name">
    </div>
    <%# ポジション %>
    <%# TODO: チェックボックスにし、全ポジション表示 %>
    <div class="mb-3">
      <label for="position" class="form-label">ポジション</label>
      <div class="form-check form-switch">
        <input class="form-check-input" type="checkbox" id="subPositionSwitch">
        <label class="form-check-label" for="subPositionSwitch">サブポジションを含む</label>
      </div>
      <input type="search" class="form-control" id="position" autocomplete="name">
    </div>
    <%# 検索ボタン %>
    <input type="submit" class="btn btn-primary" value="検索">
  </form>
  <%# 一覧表示部 %>
  <table class="table table-striped caption-top">
    <thead>
      <tr>
        <th scope="col" class="align-middle">#</th>
        <th scope="col" class="align-middle">選手名</th>
        <th scope="col" class="align-middle">守備位置</th>
        <th scope="col" class="align-middle">投打</th>
        <th scope="col" class="align-middle">弾道</th>
        <th scope="col" class="align-middle">ミート</th>
        <th scope="col" class="align-middle">パワー</th>
        <th scope="col" class="align-middle">走力</th>
        <th scope="col" class="align-middle">肩力</th>
        <th scope="col" class="align-middle">守備力</th>
        <th scope="col" class="align-middle">捕球</th>
        <th scope="col" class="align-middle">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @players.each do |player| %>
        <tr>
          <th scope="row" class="align-middle">1</th>
          <td class="align-middle"><%= player.player_name %></td>
          <td class="align-middle"><%= display_positions(player) %></td>
          <td class="align-middle"><%= display_left_and_right(player.throws) %>投<%= display_left_and_right(player.bats) %>打</td>
          <td class="align-middle">
            <span class="me-2 h5"><%= display_trajectory(player.pawapuro_fielder.trajectory) %></span>
            <%= player.pawapuro_fielder.trajectory %>
          </td>
          <td class="align-middle">
            <%= display_alphabet(player.pawapuro_fielder.meat) %>
            <%= player.pawapuro_fielder.meat %>
          </td>
          <td class="align-middle">
            <%= display_alphabet(player.pawapuro_fielder.power) %>
            <%= player.pawapuro_fielder.power %>
          </td>
          <td class="align-middle">
            <%= display_alphabet(player.pawapuro_fielder.running) %>
            <%= player.pawapuro_fielder.running %>
          </td>
          <td class="align-middle">
            <%= display_alphabet(player.pawapuro_fielder.arm_strength) %>
            <%= player.pawapuro_fielder.arm_strength %>
          </td>
          <td class="align-middle">
            <%= display_alphabet(player.pawapuro_fielder.defense) %>
            <%= player.pawapuro_fielder.defense %>
          </td>
          <td class="align-middle">
            <%= display_alphabet(player.pawapuro_fielder.catching) %>
            <%= player.pawapuro_fielder.catching %>
          </td>
          <td class="align-middle">
            <%# <button type="button" id="my_button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#playerDetailsModal">
              詳細
            </button> %>
            <%= link_to '詳細modal', details_pawapuro_path(player), remote: true, class: 'btn btn-primary details-button', id: "details_#{player.id}", data: { turbo: false, toggle: 'modal', target: '#playerDetailsModal' } %>
            <button type="button" class="btn btn-danger">削除</button>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%# 選手詳細モーダル %>
<%#= render 'player_details_modal' %>